Dtk--Widget--DTextEdit {
    color: #fff;
    border-radius: 8px;
    background-color: rgba(255, 255, 255, 26);/*use as outside border*/
}

Dtk--Widget--DTextEdit[alert="true"] QFrame#TextEditInsideFrame{
    border-color: #FF8F00;
}

QFrame#TextEditInsideFrame {/*outside frame*/
    background-color: rgba(255, 255, 255, 0.06);
    border: 1px solid rgba(255, 255, 255, 0.10);
    border-radius: 8px;
}
