
Dtk--Widget--DOption {
    margin:0 10px;
    padding:0 10px;
    qproperty-checkedIcon:url(:/images/dark/images/tick_transparent.png);
}

Dtk--Widget--DOption[checked="true"] {
    background-color: rgba(0, 150, 255, 0.14);
    border-radius:8px;
    qproperty-checkedIcon:url(:/images/dark/images/tick_hover.png);
}

Dtk--Widget--DOption #OptionName {
    color: #b4b4b4;
}

Dtk--Widget--DOption #OptionName:hover {
    color: white;
}

Dtk--Widget--DOption[checked="true"] #OptionName {
    color: #2ca7f8;
}
