#DSettingsDialog{
    qproperty-backgroundColor: rgba(30, 31, 35, 0.88);
    qproperty-borderColor: rgba(255, 255, 255, 0.06);
}

#Navigation{
    border: none;
    border-right: 1px solid rgba(255,255,255,0.08);
}

#NavigationBar{
    border: none;
}

#ButtonGroupSingle {
    border: 1px solid rgba(255, 255, 255, 0.08);
    border-radius: 8.0px;
}
#ButtonGroupBegin {
    border: 1px solid rgba(255, 255, 255, 0.08);
    border-top-left-radius: 8.0px;
    border-bottom-left-radius: 8.0px;
}
#ButtonGroupBegin:checked {
    background-color: rgba(0, 150, 255, 0.75);
    border: solid 1px rgba(0, 150, 255, 0.50);
}
#ButtonGroupMiddle {
    border-top: 1px solid rgba(255, 255, 255, 0.08);
    border-bottom: 1px solid rgba(255, 255, 255, 0.08);
    border-right: 1px solid rgba(255, 255, 255, 0.08);
}
#ButtonGroupMiddle:checked {
    background-color: rgba(0, 150, 255, 0.75);
    border: solid 1px rgba(0, 150, 255, 0.50);
}
#ButtonGroupEnd {
    border: 1px solid rgba(255, 255, 255, 0.08);
    border-left: none;
    border-top-right-radius: 8.0px;
    border-bottom-right-radius: 8.0px;
}
#ButtonGroupEnd:checked {
    background-color: rgba(0, 150, 255, 0.75);
    border: solid 1px rgba(0, 150, 255, 0.50);
}

#DSettingsDialogClose{
    qproperty-normalPic: url(:/images/dark/images/window/close_normal.svg);
    qproperty-hoverPic: url(:/images/dark/images/window/close_hover.svg);
    qproperty-pressPic: url(:/images/dark/images/window/close_press.svg);
}
