Dtk--Widget--DPasswdEditAnimated {
    border-width: 1px;
    border-style: solid;
    border-radius: 8px;
    border-color: rgba(255,255,255,.10);
    background-color: rgba(255,255,255,0.06);
}

Dtk--Widget--DPasswdEditAnimated:focus {
    border-color: rgba(0, 150, 255, 0.45);
}

Dtk--Widget--DPasswdEditAnimated[editFocus="true"] {
    border-color: #2CA7F8;
}

Dtk--Widget--DPasswdEditAnimated[alert="true"] {
    border-color: #FF8F00;
}

Dtk--Widget--DPasswdEditAnimated #KeyboardButton {
    qproperty-normalPic: url(:/images/dark/images/keyboard-normal.svg);
    qproperty-hoverPic: url(:/images/dark/images/keyboard-hover.svg);
    qproperty-pressPic: url(:/images/dark/images/keyboard-clicked.svg);
}

Dtk--Widget--DPasswdEditAnimated #PasswdEdit {

}

Dtk--Widget--DPasswdEditAnimated #Capslock {

}

Dtk--Widget--DPasswdEditAnimated #EyeButton {
    qproperty-normalPic: url(:/images/dark/images/pw-visible-normal.svg);
    qproperty-hoverPic: url(:/images/dark/images/pw-visible-hover.svg);
    qproperty-pressPic: url(:/images/dark/images/pw-visible-clicked.svg);
}

Dtk--Widget--DPasswdEditAnimated #SubmitButton {
    qproperty-normalPic: url(:/images/dark/images/submit-normal.svg);
    qproperty-hoverPic: url(:/images/dark/images/submit-hover.svg);
    qproperty-pressPic: url(:/images/dark/images/submit-clicked.svg);
}

Dtk--Widget--DPasswdEditAnimated #InvalidTip {
    qproperty-backgroundColor: rgba(255,255,255,.3);
}
