Dtk--Widget--DButtonList {
    background-color: #1A1B1B;
    border: none;
    outline: none;
}

Dtk--Widget--DButtonList::item {
    border: none;
    outline: none;
}

Dtk--Widget--DButtonList QPushButton:hover{
    color: white;
}

Dtk--Widget--DButtonList QFrame#BorderFrame{
  background-color: transparent;
}

Dtk--Widget--DButtonList QPushButton{
    background-color: transparent;
    color: #b4b4b4;
    border: none;
    border-radius: 8px;
    text-align: left center;
    padding-left: 40px;
    margin: 2px 4px;
}

Dtk--Widget--DButtonList QPushButton:hover{
    background-color: rgba(255, 255, 255, 0.06);
}

Dtk--Widget--DButtonList QPushButton:checked{
    background-color: rgba(0, 150, 255, 0.16);
    color: #4cc2ff;
}

Dtk--Widget--DButtonList QPushButton:checked[state="OnlyOne"]{
    background-color: transparent;
    color:#01BDFF;
}

Dtk--Widget--DButtonList QPushButton:checked[state="normal"]{
    background-color: lightblack;
    color:#01BDFF;
}
