Dtk--Widget--DBaseButton {
    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,
                            stop: 0 #2E3238,
                            stop: 1.0 #1B1E23);
    border-width: 1px;
    border-style: solid;
    border-radius: 8px;
    border-color: rgba(255, 255, 255, 0.08);
    padding: 0 12px;
    font-size: 13px;
}

Dtk--Widget--DBaseButton:hover {
    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,
                        stop: 0 #3A4149,
                        stop: 1.0 #24292F);
    border-color: rgba(0, 150, 255, 0.35);
}

Dtk--Widget--DBaseButton:pressed {
    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,
                        stop: 0 #1C2025,
                        stop: 1.0 #31373E);
}

Dtk--Widget--DBaseButton:flat {
    border: none; /* no border for a flat push button */
}


QFrame#ButtonInsideFrame {
    background-color: transparent;
    border-top-width: 1px;
    border-style: solid;
    border-radius: 3;
    border-top-color: rgba(255, 255, 255, 26);
}
