Dtk--Widget--DSearchEdit {
    border-radius: 8px;
}

Dtk--Widget--DSearchEdit #SearchIcon {
    background-color:transparent;
    margin: 2 -1 2 4 px;
    border-image:url(:/images/dark/images/search.svg);
}

Dtk--Widget--DSearchEdit #ClearIcon {
    background-color:transparent;
    qproperty-normalPic:url(:/images/dark/images/input_clear_normal.svg);
    qproperty-hoverPic:url(:/images/dark/images/input_clear_hover.svg);
    qproperty-pressPic:url(:/images/dark/images/input_clear_press.svg);
}

Dtk--Widget--DSearchEdit #Edit {
    background-color:transparent;
    border-radius:0;
    color:#fff;
    padding-right:15px;
    padding-bottom: 1px;
}

Dtk--Widget--DSearchEdit QFrame#DEditInsideFrame {
    background-color: rgba(255,255,255,0.06);
    border: 1px solid rgba(255,255,255,0.10);
    border-radius: 8px;
    border-color: rgba(255,255,255,0.10);
}

Dtk--Widget--DSearchEdit:focus QFrame#DEditInsideFrame {
    border-color: rgba(0, 150, 255, 0.45);
}

Dtk--Widget--DSearchEdit #PlaceHolder {
    color:white;
    margin:0 0 0 3px;
    font-size:12px;
}
