QLabel#ProductNameLabel {
    font-size:18px;
    color: #f0f0f0;
}

QLabel#VersionLabel {
    font-size:12px;
    color: #999999;
}

QLabel#WebsiteLabel {
    font-size:13px;
    color: #4cc2ff;
}

QLabel#AcknowledgementLabel {
    font-size:13px;
    color: #4cc2ff;
}

QLabel#DescriptionLabel {
    font-size:11px;
    font-weight: normal;
    color:#c0c0c0;
    border: none;
}

QLabel#LicenseLabel {
    font-size:11px;
    font-weight: normal;
    color:#c0c0c0;
    border: none;
}
