Dtk--Widget--DTitlebar {
    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,
                stop:0 rgba(255,255,255,0.72), stop:1 rgba(248,249,252,0.52));
}

Dtk--Widget--DTitlebar[transparent=true] {
    background: transparent;
}

Dtk--Widget--DWindowCloseButton {
    qproperty-normalPic: url(:/images/light/images/window/close_normal.svg);
    qproperty-hoverPic: url(:/images/light/images/window/close_hover.svg);
    qproperty-pressPic: url(:/images/light/images/window/close_press.svg);
}

#DTitlebarDWindowQuitFullscreenButton {
    qproperty-normalPic: url(:/images/light/images/window/quit_fullscreen_normal.svg);
    qproperty-hoverPic: url(:/images/light/images/window/quit_fullscreen_hover.svg);
    qproperty-pressPic: url(:/images/light/images/window/quit_fullscreen_press.svg);
}
