Dtk--Widget--DBaseButton {
    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,stop: 0 #4AA8FF, stop: 1.0 #1B7BFF);
    border-width: 1px;
    border-color: rgba(0, 110, 255, 0.35);
    border-style: solid;
    border-radius: 8px;
    padding: 0 12px;
    font-size: 13px;
    color: white;
}

Dtk--Widget--DBaseButton:hover{
    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,stop: 0 #6CB8FF, stop: 1.0 #2D8FFF);
    border-color: rgba(0, 140, 255, 0.50);
}

Dtk--Widget--DBaseButton:pressed{
    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,stop: 0 #2A86F0, stop: 1.0 #1A6FD8);
}

Dtk--Widget--DBaseButton:disabled {
    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,stop: 0 rgba(96,160,255,0.45), stop: 1.0 rgba(27,123,255,0.45));
    border-color: rgba(0, 110, 255, 0.15);
}

Dtk--Widget--DBaseButton:flat {
    border: none; /* no border for a flat push button */
}

QFrame#ButtonInsideFrame {
    background-color: transparent;
    border-top-width: 1px;
    border-style: solid;
    border-radius: 3px;
    border-top-color: rgba(255, 255, 255, 0.1);
}






