Dtk--Widget--DButtonList {
    background-color: #ffffff;
    border: none;
}

Dtk--Widget--DButtonList QPushButton:hover{
    color: black;
}

Dtk--Widget--DButtonList QFrame#BorderFrame{
  background-color: transparent;
}

Dtk--Widget--DButtonList QFrame#BorderFrame[state="checked"]{
  background-color: transparent;
}

Dtk--Widget--DButtonList QPushButton{
    background-color: transparent;
    color: #666666;
    border: none;
    border-radius: 8px;
    text-align: left center;
    padding-left: 40px;
    margin: 2px 4px;
}

Dtk--Widget--DButtonList QPushButton:hover{
    background-color: rgba(0, 0, 0, 0.04);
}

Dtk--Widget--DButtonList QPushButton:checked{
    background-color: rgba(0, 120, 255, 0.10);
    color: #0078d4;
}
