Dtk--Widget--DLineEdit {
    color: #1a1a1a;
    border-radius: 8px;
    margin-left: 3px;
    background-color: rgba(255, 255, 255, 26);/*use as outside border*/
}

Dtk--Widget--DLineEdit[alert="true"] QFrame#LineEditInsideFrame{
    border-color: #FF8F00;
}

QFrame#LineEditInsideFrame {/*outside frame*/
    background-color: rgba(255, 255, 255, 0.72);
    border: 1px solid rgba(0, 0, 0, 0.10);
    border-radius: 8px;
}

Dtk--Widget--DLineEdit:focus QFrame#LineEditInsideFrame {
    border-color: rgba(0, 120, 255, 0.45);
}

Dtk--Widget--DLineEdit #IconButton {
    border: 0px solid;
    border-left: 1px solid rgba(0, 0, 0, 20%);
    margin: 1px 0px 2px 0px;
}

Dtk--Widget--DLineEdit[alert="true"] #IconButton{
    border-color: #FF8F00;
}

Dtk--Widget--DLineEdit #ClearButton {
    qproperty-normalPic: ":/images/light/images/input_clear_normal.svg";
    qproperty-hoverPic: ":/images/light/images/input_clear_hover.svg";
    qproperty-pressPic: "/images/light/images/input_clear_press.svg";
    margin-right: 4px;
}

#AlertTooltip QLabel {
    color: #FF8F00;
}
